from typing import List, Optional

from pydantic import BaseModel, Field


class RubricItem(BaseModel):
    minScore: int = Field(..., description="Minimum score for this proficiency level")
    maxScore: int = Field(..., description="Maximum score for this proficiency level")
    proficiency: str = Field(..., description="Proficiency label (e.g. Poor, Average, Good, Excellent)")
    criteria: str = Field(..., description="Description of what the student must demonstrate")


class FeedTokenUsage(BaseModel):
    embedding_tokens: int = Field(..., description="Total tokens used for text embedding")
    embedding_cost_usd: float = Field(..., description="Cost of embedding in USD")
    vision_tokens: int = Field(..., description="Total vision tokens used for image descriptions")
    vision_cost_usd: float = Field(..., description="Cost of vision model in USD")
    total_cost_usd: float = Field(..., description="Total estimated cost in USD")


class AssessTokenUsage(BaseModel):
    embedding_tokens: int = Field(..., description="Tokens used for vector search embeddings")
    embedding_cost_usd: float = Field(..., description="Cost of embedding in USD")
    vision_tokens: int = Field(..., description="Tokens used for vision model (image extraction)")
    vision_cost_usd: float = Field(..., description="Cost of vision model in USD")
    completion_input_tokens: int = Field(..., description="Input tokens sent to the LLM")
    completion_output_tokens: int = Field(..., description="Output tokens generated by the LLM")
    completion_cost_usd: float = Field(..., description="Cost of LLM completion in USD")
    total_cost_usd: float = Field(..., description="Total estimated cost in USD")


class RetrievedSource(BaseModel):
    source: str = Field(..., description="Source filename from vector DB")
    page: int | None = Field(None, description="Slide or page number (null for documents fed before page tracking was added)")
    content: str = Field(..., description="Text content of the retrieved chunk")


class SourceItem(BaseModel):
    title: str = Field(..., description="Title of the web source")
    url: str = Field(..., description="URL of the source")
    content: str = Field(..., description="First ~20 words retrieved from the source URL")


class WebSearchCitation(BaseModel):
    url: str = Field(..., description="URL cited by the web search tool")
    title: str = Field("", description="Title of the cited page (if provided by the tool)")


class WebSearchDebug(BaseModel):
    queries: List[str] = Field(default_factory=list, description="Search queries the model issued to the web search tool")
    citations: List[WebSearchCitation] = Field(default_factory=list, description="URLs the web search tool actually cited (more reliable than model-written sources)")


class EvaluationResult(BaseModel):
    reasoning: str = Field(..., description="Logical reasoning behind the score (max 2 sentences, written in the student's language)")
    score: float = Field(..., description="Numerical score based on the rubric")
    confidence: float = Field(..., description="AI confidence level (0–100)")
    feedback: str = Field(..., description="Constructive feedback for improvement (empty string when score=0)")
    sources: List[SourceItem] = Field(default_factory=list, description="Web sources cited (populated only when web search was used)")
    web_search: Optional[WebSearchDebug] = Field(None, description="Raw web search activity (queries + cited URLs); only present when DEBUG=true")
